####################################################################
# what to do
# number of gals to make per file
Ngals: 4000

# not used by egret. Implies total number of galaxies is 80,000,000
Nfiles: 5000

# not used by egret. Seconds per galaxy.  We will also add the
# 5 minute overhead
# double the time to be sure
sec_per: 6.0

# output files will look like
#     test_medsXXXXXX.fits.fz
#     test_psfXXXXXX.fits
# for
#     output_base: 'test'
# or
#     output_base: 'test_'

# directory must already exist
output_base: "/u/ki/esheldon/lensing/egretsims/v06/work/data/v06"


####################################################################
# this is used to seed everything
# by generating more seeds for all other generators just once
global_seed: 4552

####################################################################
# these options can be used for parallel sim generation
# they get set to
#     num_seeds: 1
#     seed_index: 0
# by default
#
# It is best to specify them on the command line to egret as
#     egret --num-seeds=100 --seed-index=12 <config.yaml>
# so you can submit many jobs
#
# make initial seed arrays for PSF and Gal makers of this length
#num_seeds: 100
#
# use this seed (zero-indexed position) in seed arrays for seeding the Gal and PSF makers
#seed_index: 12 

####################################################################
# image and obs properties
seeing: 0.55
n_epochs: 1 # doesn't work yet...
pixel_scale: 0.265

####################################################################
# stamp sizes
min_size: 32
max_size: 48

# you can just list a set of desired sizes here
#     sizes: [32,36,48] 
# egret usually just choses itself based on the object and how FFT-friendly a size is

####################################################################
# this applies a shear
g: [-0.08,0.0]

####################################################################
# make galaxies like this
# options are specific to the type of galaxy maker
# these objects can also pull from the global options above
galaxymaker:
    type: "great3-cosmos"
    # True because this is the shallow data
    use_great3_noise: True
    save_catalog: True
    preload: True

####################################################################
# make PSFs like this
# options are specific to the type of PSF maker
# these objects can also pull from the global options above
psfmaker:
    type: "des-psf"
    size: 32

